const Images = {
  'active-checkbox': require('../../assets/images/icons/active-checkbox.png'),
  'active-radio': require('../../assets/images/icons/active-radio.png'),
  angry: require('../../assets/images/icons/angry.png'),
  'angry-2': require('../../assets/images/icons/angry-2.png'),
  'arrow-left-circle': require('../../assets/images/icons/arrow-left-circle.png'),
  'arrow-right-circle': require('../../assets/images/icons/arrow-right-circle.png'),
  background: require('../../assets/images/icons/background.png'),
  bag: require('../../assets/images/icons/bag.png'),
  boxes: require('../../assets/images/icons/boxes.png'),
  bottom_semi_circle: require('../../assets/images/icons/bottom_semi_circles.png'),
  calendar: require('../../assets/images/icons/calendar.png'),
  cbt: require('../../assets/images/icons/cbt.png'),
  check: require('../../assets/images/icons/check.png'),
  checkbox: require('../../assets/images/icons/checkbox.png'),
  'chevron-down': require('../../assets/images/icons/chevron-down.png'),
  'circle-check': require('../../assets/images/icons/circle-check.png'),
  'circle-check-box': require('../../assets/images/icons/circle-check-box.png'),
  dairy: require('../../assets/images/icons/diary.png'),
  document: require('../../assets/images/icons/Document.png'),
  ellipse: require('../../assets/images/icons/ellipse.png'),
  'ellipse-2': require('../../assets/images/icons/ellipse-2.png'),
  'empty-mood': require('../../assets/images/icons/empty-mood.png'),
  excited: require('../../assets/images/icons/excited.png'),
  'eye-off': require('../../assets/images/icons/eye-off.png'),
  frame: require('../../assets/images/icons/frame.png'),
  gradient: require('../../assets/images/icons/gradient.png'),
  happy: require('../../assets/images/icons/happy.png'),
  'happy-2': require('../../assets/images/icons/happy-2.png'),
  'happy-purple': require('../../assets/images/icons/happy-purple.png'),
  'happy-white': require('../../assets/images/icons/happy-white.png'),
  headphones: require('../../assets/images/icons/headphones.png'),
  'header-icon': require('../../assets/images/icons/header-icon.png'),
  heart: require('../../assets/images/icons/heart.png'),
  'help-circle': require('../../assets/images/icons/help-circle.png'),
  journal: require('../../assets/images/icons/journal.png'),
  line: require('../../assets/images/icons/line.png'),
  lock: require('../../assets/images/icons/lock.png'),
  logo: require('../../assets/images/icons/logo.png'),
  'logo-white': require('../../assets/images/icons/logo-white.png'),
  'long-arrow': require('../../assets/images/icons/long-arrow.png'),
  'mood-1': require('../../assets/images/icons/mood-1.png'),
  'mood-2': require('../../assets/images/icons/mood-2.png'),
  'mood-3': require('../../assets/images/icons/mood-3.png'),
  'mood-4': require('../../assets/images/icons/mood-4.png'),
  'mood-5': require('../../assets/images/icons/mood-5.png'),
  notification: require('../../assets/images/icons/notification.png'),
  paper: require('../../assets/images/icons/paper.png'),
  play: require('../../assets/images/icons/play.png'),
  'play-2': require('../../assets/images/icons/play-2.png'),
  plus: require('../../assets/images/icons/plus.png'),
  phone: require('../../assets/images/icons/phone.png'),
  'phone-calling': require('../../assets/images/icons/phone-calling.png'),
  'profile-group': require('../../assets/images/icons/profile-group.png'),
  'profile-image': require('../../assets/images/icons/profile-image.png'),
  ptsd: require('../../assets/images/icons/ptsd.png'),
  sad: require('../../assets/images/icons/sad.png'),
  'sad-2': require('../../assets/images/icons/sad-2.png'),
  search: require('../../assets/images/icons/search.png'),
  shield: require('../../assets/images/icons/shield.png'),
  smile: require('../../assets/images/icons/smile.png'),
  text: require('../../assets/images/icons/text.png'),
  'time-circle': require('../../assets/images/icons/time-circle.png'),
  'top-video': require('../../assets/images/icons/top-video.png'),
  radio: require('../../assets/images/icons/radio.png'),
  'read-1': require('../../assets/images/icons/read-1.png'),
  'read-2': require('../../assets/images/icons/read-2.png'),
  'watch-recently': require('../../assets/images/icons/watch-recently.png'),
  x: require('../../assets/images/icons/x.png'),
  'video-player': require('../../assets/images/icons/video-player.png'),
  videos: require('../../assets/images/icons/videos.png'),
  voice: require('../../assets/images/icons/voice.png'),
  'voice-note': require('../../assets/images/icons/voice-note.png'),
  users: require('../../assets/images/icons/users.png'),
  upload: require('../../assets/images/icons/upload.png'),

  //note-taking icons
  'active-note-text': require('../../assets/images/note-options/active-text.png'),
  'active-note-image': require('../../assets/images/note-options/active-image.png'),
  'note-image': require('../../assets/images/note-options/image.png'),
  'note-mood': require('../../assets/images/note-options/mood.png'),
  'note-text': require('../../assets/images/note-options/text.png'),
  'note-video': require('../../assets/images/note-options/video.png'),
  'note-voice': require('../../assets/images/note-options/voice.png'),

  //frames
  'journal-frame': require('../../assets/images/journal-frame.png'),

  //bottom tabs
  activity: require('../../assets/images/bottom-tabs/activity.png'),
  category: require('../../assets/images/bottom-tabs/category.png'),
  'category-active': require('../../assets/images/bottom-tabs/category-active.png'),
  home: require('../../assets/images/bottom-tabs/home.png'),
  'home-active': require('../../assets/images/bottom-tabs/home-active.png'),
  profile: require('../../assets/images/bottom-tabs/profile.png'),
  settings: require('../../assets/images/bottom-tabs/settings.png'),

  //cbt
  'cbt-1': require('../../assets/images/cbt/cbt-1.png'),
  'cbt-2': require('../../assets/images/cbt/cbt-2.png'),
  'cbt-3': require('../../assets/images/cbt/cbt-3.png'),
  'cbt-4': require('../../assets/images/cbt/cbt-4.png'),
};

export default Images;
