const Images = {
  'active-checkbox': require('../../assets/images/icons/active-checkbox.png'),
  'active-radio': require('../../assets/images/icons/active-radio.png'),
  angry: require('../../assets/images/icons/angry.png'),
  background: require('../../assets/images/icons/background.png'),
  boxes: require('../../assets/images/icons/boxes.png'),
  bottom_semi_circle: require('../../assets/images/icons/bottom_semi_circles.png'),
  calendar: require('../../assets/images/icons/calendar.png'),
  check: require('../../assets/images/icons/check.png'),
  checkbox: require('../../assets/images/icons/checkbox.png'),
  'chevron-down': require('../../assets/images/icons/chevron-down.png'),
  dairy: require('../../assets/images/icons/diary.png'),
  ellipse: require('../../assets/images/icons/ellipse.png'),
  excited: require('../../assets/images/icons/excited.png'),
  'eye-off': require('../../assets/images/icons/eye-off.png'),
  gradient: require('../../assets/images/icons/gradient.png'),
  happy: require('../../assets/images/icons/happy.png'),
  headphones: require('../../assets/images/icons/headphones.png'),
  heart: require('../../assets/images/icons/heart.png'),
  'help-circle': require('../../assets/images/icons/help-circle.png'),
  line: require('../../assets/images/icons/line.png'),
  logo: require('../../assets/images/icons/logo.png'),
  'logo-white': require('../../assets/images/icons/logo-white.png'),
  'long-arrow': require('../../assets/images/icons/long-arrow.png'),
  'mood-1': require('../../assets/images/icons/mood-1.png'),
  'mood-2': require('../../assets/images/icons/mood-2.png'),
  'mood-3': require('../../assets/images/icons/mood-3.png'),
  'mood-4': require('../../assets/images/icons/mood-4.png'),
  notification: require('../../assets/images/icons/notification.png'),
  'profile-group': require('../../assets/images/icons/profile-group.png'),
  'profile-image': require('../../assets/images/icons/profile-image.png'),
  sad: require('../../assets/images/icons/sad.png'),
  search: require('../../assets/images/icons/search.png'),
  shield: require('../../assets/images/icons/shield.png'),
  smile: require('../../assets/images/icons/smile.png'),
  radio: require('../../assets/images/icons/radio.png'),
  x: require('../../assets/images/icons/x.png'),
  users: require('../../assets/images/icons/users.png'),

  //bottom tabs
  activity: require('../../assets/images/bottom-tabs/activity.png'),
  category: require('../../assets/images/bottom-tabs/category.png'),
  'category-active': require('../../assets/images/bottom-tabs/category-active.png'),
  home: require('../../assets/images/bottom-tabs/home.png'),
  'home-active': require('../../assets/images/bottom-tabs/home-active.png'),
  profile: require('../../assets/images/bottom-tabs/profile.png'),
  settings: require('../../assets/images/bottom-tabs/settings.png'),
};

export default Images;
